language: node_js
node_js:
  - '0.10'
script: node_modules/karma/bin/karma start test/karma.conf.js --single-run    
before_script:
  - 'npm install -g bower'
  - 'bower install'
after_script: NODE_ENV=sudo cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && sudo rm -rf coverage

notifications:
  email:
    recipients:
      - emascarinas@gmail.com
    on_failure: always
  
